### ISSUE TITLE
Can't build production configuration

### ISSUE THREAD

**Issue by Josema** [FormidableLabs/electron-webpack-dashboard#8] opened 2017-08-17 18:45 UTC
```
$ npm run build

> wedontneedbanks@1.0.0 build /Users/enzo/Copy/projects/myproject/web
> webpack --config=./webpack/production.js --optimize-minimize --progress --colors --display-error-details

 95% emitting/Users/enzo/Copy/projects/myproject/web/node_modules/webpack-dashboard/plugin/index.js:57
      inspectpack[action]({
                 ^

TypeError: Cannot read property 'sizes' of undefined
    at Promise.all.bundles.map.bundle (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack-dashboard/plugin/index.js:57:18)
    at Array.map (native)
    at INSPECTPACK_INDEPENDENT_ACTIONS.forEach.action (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack-dashboard/plugin/index.js:56:25)
    at Array.forEach (native)
    at getBundleMetrics (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack-dashboard/plugin/index.js:55:35)
    at Compiler.compiler.plugin.stats (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack-dashboard/plugin/index.js:220:7)
    at Compiler.applyPlugins (/Users/enzo/Copy/projects/myproject/web/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/enzo/Copy/projects/myproject/web/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/enzo/Copy/projects/myproject/web/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/enzo/Copy/projects/myproject/web/node_modules/webpack/lib/Compiler.js:360:15)
    at /Users/enzo/Copy/projects/myproject/web/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/enzo/Copy/projects/myproject/web/node_modules/async/dist/async.js:998:13)
    at /Users/enzo/Copy/projects/myproject/web/node_modules/async/dist/async.js:906:16
    at /Users/enzo/Copy/projects/myproject/web/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by kenwheeler** [comment] 2017-08-17 19:19
Closing as a duplicate of #1 , getting this sorted out now

**Closed by kenwheeler** 2017-08-17 19:19 UTC

**Comment by SaraVieira** [comment] 2017-08-17 19:59
I was here to say the same thing but awesome for the quick response @kenwheeler !
